'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmSelectQuestionTest
    
    '''<summary>
    '''scriptmanager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents scriptmanager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''lblTestTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTestTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlTestQuestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTestQuestion As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UCabcd1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCabcd1 As Global.TESCO_TMS3.UCTestABCD
    
    '''<summary>
    '''UCMaching control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCMaching As Global.TESCO_TMS3.UCMaching
    
    '''<summary>
    '''UCPicture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCPicture As Global.TESCO_TMS3.UCPicture
    
    '''<summary>
    '''UCyesno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCyesno As Global.TESCO_TMS3.UCyesno
    
    '''<summary>
    '''UCWriting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCWriting As Global.TESCO_TMS3.UCWriting
    
    '''<summary>
    '''txtQuestion_no control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuestion_no As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblIsShowAnswer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIsShowAnswer As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCourseID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCourseID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTargetPercent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTargetPercent As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblQuestionQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQuestionQty As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlSummaryFalse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSummaryFalse As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblCorrectScoreFalse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCorrectScoreFalse As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTotalScoreFalse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalScoreFalse As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTotalQuestionFalse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalQuestionFalse As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblResultPercentFalse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResultPercentFalse As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnBackFalse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBackFalse As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlSummaryTrue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSummaryTrue As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblCorrectScoreTrue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCorrectScoreTrue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTotalScoreTrue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalScoreTrue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTotalQuestionTrue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalQuestionTrue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblResultPercentTrue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResultPercentTrue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnBackTrue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBackTrue As Global.System.Web.UI.WebControls.LinkButton
End Class
